name: Release

on:
  push:
    # branches:
    #   - master
    tags:
      - "*"

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Checkout
        uses: actions/checkout@master

      - name: get
        run: |
          export GOBIN=$GOROOT/bin
          go get github.com/freecracy/help
          echo $GOBIN
          mv $GOBIN/help .
      # - name: Get dependencies
      #   run: |
      #     export GO111MODULE=on
          #export GOBIN=$(go env GOPATH)/bin
          #export PATH=$PATH:$(go env GOPATH)/bin
          #go get -v -t -d ./...
          # if [ -f Gopkg.toml ]; then
          #   curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          #   dep ensure
          # fi

      # - name: Build
      #   run: |
      #     export GO111MODULE=on
      #     go mod init
      #     go mod tidy
      #     go build -v .

      - name: tar
        run: |
            mkdir help-${GITHUB_REF:10}
            mv help help-${GITHUB_REF:10}
            tar -cvzf help.linux.tar.gz help-${GITHUB_REF:10}

      - name: publish
        #if: contains(github.ref, 'refs/tags')
        uses: ./.github/actions/release
        env:
          GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }}
        with:
          args: help.linux.tar.gz


