name: Release

on: push

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
          
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
          fi
          
      - name: Build
        run: |
          go build -v .
          tar -cvzf help.linux.tar.gz help
        
      - name: Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          file: help.linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }}